Fix aioredis version
naumanni/naumanni-server pull request #7
Opened 2017-06-22 10:18 UTC by pe-ter-

due to wrong version

2017-06-22 10:27 UTC, shnjp requested changes

2017-06-22 10:27 UTC, shnjp commented on setup.py
> +        'aioredis==0.3.1',
`<1.0`
の方が良くない？

2017-07-07 09:29 UTC, pe-ter- commented
なおしました

2017-07-26 09:34 UTC, shnjp approved these changes

2017-07-26 09:35 UTC, merged